In [1]:
import pandas as pd

In [14]:
a = pd.read_csv('토양특성조사표.csv')
b = pd.read_csv('임분조사표.csv')
a.columns

Index(['집락번호', '표본점번호', '조사차기', '조사구 위치', '유기물층 두께(cm)\n낙엽층',
       '유기물층 두께(cm)\n분해/부식층', '건중량(g)\n낙엽층', '건중량(g)\n분해/부식층', '토심(cm)\nA층',
       '토심(cm)\nB층', '토심(cm)\n유효토심', '견밀도(mm)\nA층', '견밀도(mm)\nB층',
       '견습도(%)\nA층', '견습도(%)\nB층', '낙엽층\n시료 채취 여부', '분해/부식층\n시료 채취 여부',
       'A층\n시료 채취 여부', 'B층\n시료 채취 여부', '0~10cm\n토양시료 깊이', '10~20cm\n토양시료 깊이',
       '20~30cm\n토양시료 깊이', '비고'],
      dtype='object')

In [15]:
b.columns

Index(['집락번호', '표본점번호', '조사차기', '조사연도', '조사일자', '시도코드', '시군구코드', '읍면동코드',
       '광역시도', '시군구', '읍면동', '도엽번호', '좌표N', '좌표E', '도로로부터의거리', '해발고', '경사',
       '지형코드', '지형', '사면위치코드', '사면위치', '지형(산림식생)\n코드', '지형(산림식생)', '8방위코드',
       '8방위코드명', '방위', '임상코드', '임상', '수관밀도코드', '수관밀도', '경급코드', '경급', '영급코드',
       '영급', '소유코드', '소유', '임종코드', '임종', '지종코드', '지종', '갱신형태코드', '갱신형태',
       '토양형코드', '토양형', '토성(A)코드', '토성(A)', '토성(B)코드', '토성(B)', '암석노출도코드',
       '암석노출도', '침식상태코드', '침식상태', '중심수관밀도', '0도수관밀도', '120도수관밀도', '240도수관밀도',
       '수관밀도평균', '특이사항', '산림교란\n(산불)', '산림교란\n(병해충)', '산림교란\n(기상)',
       '산림교란\n(인위적)', '산림교란\n(덩굴)', '산림교란\n(기타)', '야생동물\n서식흔적', '기타\n특이사항',
       '표본점\n현지정보', '지형지물\n종류', '지형지물\n거리', '지형지물\n방위', '입력자'],
      dtype='object')

In [36]:
c = pd.merge(a,b,how='left',on='집락번호')
c.columns

Index(['집락번호', '표본점번호_x', '조사차기_x', '조사구 위치', '유기물층 두께(cm)\n낙엽층',
       '유기물층 두께(cm)\n분해/부식층', '건중량(g)\n낙엽층', '건중량(g)\n분해/부식층', '토심(cm)\nA층',
       '토심(cm)\nB층', '토심(cm)\n유효토심', '견밀도(mm)\nA층', '견밀도(mm)\nB층',
       '견습도(%)\nA층', '견습도(%)\nB층', '낙엽층\n시료 채취 여부', '분해/부식층\n시료 채취 여부',
       'A층\n시료 채취 여부', 'B층\n시료 채취 여부', '0~10cm\n토양시료 깊이', '10~20cm\n토양시료 깊이',
       '20~30cm\n토양시료 깊이', '비고', '표본점번호_y', '조사차기_y', '조사연도', '조사일자', '시도코드',
       '시군구코드', '읍면동코드', '광역시도', '시군구', '읍면동', '도엽번호', '좌표N', '좌표E',
       '도로로부터의거리', '해발고', '경사', '지형코드', '지형', '사면위치코드', '사면위치', '지형(산림식생)\n코드',
       '지형(산림식생)', '8방위코드', '8방위코드명', '방위', '임상코드', '임상', '수관밀도코드', '수관밀도',
       '경급코드', '경급', '영급코드', '영급', '소유코드', '소유', '임종코드', '임종', '지종코드', '지종',
       '갱신형태코드', '갱신형태', '토양형코드', '토양형', '토성(A)코드', '토성(A)', '토성(B)코드',
       '토성(B)', '암석노출도코드', '암석노출도', '침식상태코드', '침식상태', '중심수관밀도', '0도수관밀도',
       '120도수관밀도', '240도수관밀도', '수관밀도평균', '특이사항', '산림교란\n(산불)', '산림교란\n(병해충)',
       '산림교란\n(기상)', '산림교란\n(인위적)', '산림교란\n(덩굴)', '산림교란\n(기타)', '야생동물\n서식흔적',
       '기타\n특이사항', '표본점\n현지정보', '지형지물\n종류', '지형지물\n거리', '지형지물\n방위', '입력자'],
      dtype='object')

In [37]:
a.head()

,집락번호,표본점번호,조사차기,조사구 위치,유기물층 두께(cm)\n낙엽층,유기물층 두께(cm)\n분해/부식층,건중량(g)\n낙엽층,건중량(g)\n분해/부식층,토심(cm)\nA층,토심(cm)\nB층,...,견습도(%)\nA층,견습도(%)\nB층,낙엽층\n시료 채취 여부,분해/부식층\n시료 채취 여부,A층\n시료 채취 여부,B층\n시료 채취 여부,0~10cm\n토양시료 깊이,10~20cm\n토양시료 깊이,20~30cm\n토양시료 깊이,비고
0,124100,1241001,7,0도,1.0,2.0,0,0,7,20,...,40(적윤),40(적윤),채취,채취,채취,채취,10,10,0,NaN
1,124100,1241001,7,120도,1.5,2.0,0,0,8,30,...,35(적윤),25(적윤),채취,채취,채취,채취,10,10,20,NaN
2,132168,1321681,7,120도,0.0,0.0,0,0,0,0,...,0,0,미채취,미채취,미채취,미채취,0,0,0,NaN
3,132168,1321681,7,240도,0.0,0.0,0,0,0,0,...,0,0,미채취,미채취,미채취,미채취,0,0,0,NaN
4,148-020,148-0201,7,0도,0.6,0.3,0,0,11,33,...,20(적윤),25(적윤),채취,채취,채취,채취,10,10,10,NaN

In [49]:
a = a.loc[a['조사구 위치']=='0도']
a.head()

,집락번호,표본점번호,조사차기,조사구 위치,유기물층 두께(cm)\n낙엽층,유기물층 두께(cm)\n분해/부식층,건중량(g)\n낙엽층,건중량(g)\n분해/부식층,토심(cm)\nA층,토심(cm)\nB층,...,견습도(%)\nA층,견습도(%)\nB층,낙엽층\n시료 채취 여부,분해/부식층\n시료 채취 여부,A층\n시료 채취 여부,B층\n시료 채취 여부,0~10cm\n토양시료 깊이,10~20cm\n토양시료 깊이,20~30cm\n토양시료 깊이,비고
0,124100,1241001,7,0도,1.0,2.0,0,0,7,20,...,40(적윤),40(적윤),채취,채취,채취,채취,10,10,0,NaN
4,148-020,148-0201,7,0도,0.6,0.3,0,0,11,33,...,20(적윤),25(적윤),채취,채취,채취,채취,10,10,10,NaN
6,148200,1482001,7,0도,0.3,0.2,0,0,0,0,...,0,0,채취,채취,미채취,미채취,0,0,0,NaN
8,152368,1523681,7,0도,0.4,0.2,0,0,25,52,...,20(약건),15(약건),채취,채취,채취,채취,10,10,10,NaN
10,156380,1563801,7,0도,0.4,0.6,0,0,19,51,...,10(약건),15(약건),채취,채취,채취,채취,10,10,10,NaN

In [52]:
b = b.drop_duplicates(subset=['집락번호'])
b.head()

,집락번호,표본점번호,조사차기,조사연도,조사일자,시도코드,시군구코드,읍면동코드,광역시도,시군구,...,산림교란\n(인위적),산림교란\n(덩굴),산림교란\n(기타),야생동물\n서식흔적,기타\n특이사항,표본점\n현지정보,지형지물\n종류,지형지물\n거리,지형지물\n방위,입력자
0,112108,1121081,7,2016,20160421,46,46900,46900360,전라남도,진도군,...,NaN,NaN,NaN,NaN,NaN,1121082 : 기타(공사장) \n,NaN,NaN,NaN,fic07
4,124100,1241001,7,2016,20160713,46,46900,46900340,전라남도,진도군,...,NaN,NaN,NaN,NaN,매미소리로 전자측고기와 레이저 측정기 사용,NaN,NaN,NaN,NaN,fic17
8,124172,1241721,7,2016,20160418,46,46910,46910250,전라남도,신안군,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fic07
12,124368,1243681,7,2016,20161027,44,44825,44825340,충청남도,태안군,...,NaN,NaN,NaN,NaN,NaN,1243684 : 제지(해안가 암석지) \n,NaN,NaN,NaN,fic17
16,130-024,130-0241,7,2016,20161026,50,50130,50130250,제주도,서귀포시,...,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fic16

In [55]:
a.shape , b.shape

((183, 23), (804, 71))

In [53]:
c = pd.merge(a,b,on='집락번호')
c

,집락번호,표본점번호_x,조사차기_x,조사구 위치,유기물층 두께(cm)\n낙엽층,유기물층 두께(cm)\n분해/부식층,건중량(g)\n낙엽층,건중량(g)\n분해/부식층,토심(cm)\nA층,토심(cm)\nB층,...,산림교란\n(인위적),산림교란\n(덩굴),산림교란\n(기타),야생동물\n서식흔적,기타\n특이사항,표본점\n현지정보,지형지물\n종류,지형지물\n거리,지형지물\n방위,입력자
0,124100,1241001,7,0도,1.0,2.0,0,0,7,20,...,NaN,NaN,NaN,NaN,매미소리로 전자측고기와 레이저 측정기 사용,NaN,NaN,NaN,NaN,fic17
1,148-020,148-0201,7,0도,0.6,0.3,0,0,11,33,...,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fic41
2,148200,1482001,7,0도,0.3,0.2,0,0,0,0,...,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fic41
3,152368,1523681,7,0도,0.4,0.2,0,0,25,52,...,NaN,NaN,NaN,NaN,NaN,1523682 : 과거 작업로 \n,NaN,NaN,NaN,fic42
4,156380,1563801,7,0도,0.4,0.6,0,0,19,51,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fic42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,416292,4162921,7,0도,1.5,0.4,0,0,9,21,...,NaN,2.0,NaN,NaN,NaN,4162922 : 논 \n4162923 : 논 \n4162924 : 미륵석탑 \n,NaN,NaN,NaN,fic37
179,418236,4182361,7,0도,1.0,0.4,0,0,22,52,...,NaN,NaN,NaN,NaN,매미소리로 전자측고기와 레이저측정기 사용,NaN,NaN,NaN,NaN,fic41
180,420252,4202521,7,0도,1.1,0.3,0,0,19,35,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fic37
181,420276,4202761,7,0도,1.2,0.5,0,0,16,42,...,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fic37
182,422232,4222321,7,0도,0.7,0.4,0,0,19,52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fic41

In [56]:
c = c.drop(columns=['표본점번호_x', '조사차기_x', '조사구 위치','비고', '표본점번호_y', '조사차기_y', '조사연도', '조사일자','도로로부터의거리', '해발고', '경사', '지형코드', '지형', '사면위치코드', '사면위치', '지형(산림식생)\n코드',
       '지형(산림식생)', '8방위코드', '8방위코드명', '방위', '임상코드', '임상', '수관밀도코드', '수관밀도',
       '경급코드', '경급', '영급코드', '영급', '소유코드', '소유', '임종코드', '임종', '지종코드', '지종',
       '갱신형태코드', '갱신형태', '토양형코드', '토양형', '토성(A)코드', '토성(A)', '토성(B)코드',
       '토성(B)', '암석노출도코드', '암석노출도', '침식상태코드', '침식상태', '중심수관밀도', '0도수관밀도',
       '120도수관밀도', '240도수관밀도', '수관밀도평균', '특이사항', '산림교란\n(산불)', '산림교란\n(병해충)',
       '산림교란\n(기상)', '산림교란\n(인위적)', '산림교란\n(덩굴)', '산림교란\n(기타)', '야생동물\n서식흔적',
       '기타\n특이사항', '표본점\n현지정보', '지형지물\n종류', '지형지물\n거리', '지형지물\n방위', '입력자'])
c

,집락번호,유기물층 두께(cm)\n낙엽층,유기물층 두께(cm)\n분해/부식층,건중량(g)\n낙엽층,건중량(g)\n분해/부식층,토심(cm)\nA층,토심(cm)\nB층,토심(cm)\n유효토심,견밀도(mm)\nA층,견밀도(mm)\nB층,...,20~30cm\n토양시료 깊이,시도코드,시군구코드,읍면동코드,광역시도,시군구,읍면동,도엽번호,좌표N,좌표E
0,124100,1.0,2.0,0,0,7,20,14,7,14,...,0,46,46900,46900340,전라남도,진도군,임회면,NaN,9969xx,12392xx
1,148-020,0.6,0.3,0,0,11,33,21,14,15,...,10,50,50130,50130112,제주도,서귀포시,중문동,NaN,2969xx,14791xx
2,148200,0.3,0.2,0,0,0,0,0,0,0,...,0,46,46870,46870253,전라남도,영광군,백수읍,NaN,19969xx,14792xx
3,152368,0.4,0.2,0,0,25,52,33,9,11,...,10,44,44210,44210360,충청남도,서산시,성연면,NaN,36769xx,15192xx
4,156380,0.4,0.6,0,0,19,51,29,14,17,...,10,44,44270,44270330,충청남도,당진시,대호지면,NaN,37969xx,15593xx
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,416292,1.5,0.4,0,0,9,21,16,19,25,...,0,47,47113,47113250,경상북도,포항시북구,흥해읍,NaN,29168xx,41593xx
179,418236,1.0,0.4,0,0,22,52,34,15,19,...,10,31,31200,31200117,울산광역시,북구,신현동,NaN,23568xx,41792xx
180,420252,1.1,0.3,0,0,19,35,29,6,13,...,10,47,47130,47130320,경상북도,경주시,양남면,NaN,25168xx,41992xx
181,420276,1.2,0.5,0,0,16,42,24,18,23,...,10,47,47111,47111256,경상북도,포항시남구,오천읍,NaN,27568xx,41993xx
182,422232,0.7,0.4,0,0,19,52,32,11,16,...,10,31,31170,31170106,울산광역시,동구,주전동,NaN,23168xx,4219xx

In [57]:
c.to_csv('연료층깊이.csv',index=False)